version: "3"
services:
   app:
      build:
         context: ./
         dockerfile: Dockerfile.development
      container_name: lemoney_api
      tty: true
      volumes:
         - ./:/app
      ports:
         - "3333:3333"
      networks:
         - lemoney-network
   db:
      image: postgres
      environment:
         - "POSTGRES_PASSWORD=docker"
         - "POSTGRES_DB=123456"
      ports:
         - "5432:5432"
      networks:
         - lemoney-network
   pgadmin:
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: "daniell.oliveirra@gmail.com"
         PGADMIN_DEFAULT_PASSWORD: "docker"
      ports:
         - "5430:80"
      networks:
         - lemoney-network
   redis:
      image: redis
      ports:
         - "6379:6379"
      networks:
         - lemoney-network
networks:
   lemoney-network:
      driver: bridge
