version: "3"
services:
   app:
      build:
         context: ./
         dockerfile: Dockerfile.development
      container_name: lemoney_api
      tty: true
      volumes:
         - ./:/app
      ports:
         - "3333:3333"
      networks:
         - lemoney-network
   db:
      image: mongo
      ports:
         - "27017:27017"
      networks:
         - lemoney-network
   redis:
      image: redis
      ports:
         - "6379:6379"
      networks:
         - lemoney-network
networks:
   lemoney-network:
      driver: bridge
