version: "3"
services:
   app:
      build:
         context: ./
         dockerfile: Dockerfile.development
      container_name: cashbackapp_api
      tty: true
      volumes:
         - ./:/app
      ports:
         - "3333:3333"
      networks:
         - cashbackapp-network
   db:
      image: mongo
      ports:
         - "27017:27017"
      networks:
         - cashbackapp-network
networks:
   cashbackapp-network:
      driver: bridge
